name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Reposyu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Uygulaması (lint gibi basit testler burada olabilir)
      run: |
        echo "Test aşaması. Gerçek testler eklenecekse buraya yazılacak."

    - name: Docker kurulumu
      uses: docker/setup-buildx-action@v3

    - name: Docker image oluştur
      run: |
        docker build -t churn-fastapi .

    - name: Docker Hub'a giriş yap
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Docker image'i Docker Hub'a pushla
      run: |
        docker tag churn-fastapi ${{ secrets.DOCKERHUB_USERNAME }}/churn-fastapi:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/churn-fastapi:latest
